
USE DATABASE HRMS;

CREATE OR REPLACE SCHEMA PIPE;

CREATE OR REPLACE FILE FARMAT HRMS.PIPE.CSV_FILE_FARMATE                --Creating file formate
FILE = CSV 
FIELD_DEILMETRY = ','
SKIP_HEADER = 0
FIELD_OPTIONALLY_ENCLOSED_BY = '""'
EMPTY_FIELD_AS_NULL = TRUE

CREATE OR REPLACE STAGE HRMS.PIPE.AWS_PIPE_CSV_STAGE                   ----Creating stage
STORAGE_INTEGRATION = AWS_S3_INT
URL = 's3//learn2cloude-snowflake/snowpipe/csv/'                        ---Bucket location
FILE_FARMATE = CSV_FILE_FARMAT


LIST @AWS_PIPE_CSV_STAGE;


SELECT 
    T.$1,
    T.$2,
    T.$3,
    T.$4,
    T.$5,
    T.$6,
    T.$7,
    T.$8,
    T.$9,
    T.$10,
    T.$11,
    METADATA$FILENAME
FROM AWS_PIPE_CSV_STAGE T;

CREATE OR REPLACE TABLE EMPLOYEES_SNOWPIPE_CSV
(
EMPLOYEE_ID   NUMBER(6),
FIRST_NAME    VARCHAR(20),
LAST_NAME     VARCHAR(20),
EMAIL         VARCHAR(20),
PHONE_NUMBER  VARCHAR(20),
HIRE_DATE     VARCHAR(20),
JOB_ID        VARCHAR(20),
SALARY,        NUMBER(8,2)
COMMISION_PCT  NUMBER(2,2),
MANAGER_ID     NUMBER(6),
DEPARTMENT_ID  NUMBER(4)

);

CREATE OR REPLAC PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST = TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM AWS_PIPE_CSV_STAGE;

SHOW PIPE LIKE 'PIPE_EMPLOYEE_CSV';

SHOW PIPES;
SELECT SYSTEMS$PIPE_STATUS ('PIPE_EMPLOYEE_CSV');

LIST @AWS_PIPE_CSV_STAGE;

SELECT * FROM EMPLOYEES_SNOWPIPE_CSV;

ALTER PIPE PIPE_EMPLOYEES_CSV REFRESH;

SELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY
{
     TABLE_NAME => 'EMPLOYEES_SNOWPIPE_CSV',
     START_TIME => DATEADD(HOURS, -4, CURRENT_TIMESTAMP())
});

ALTER PIPE HRMS.PIPE.PIPE_EMPLOYEES_CSV SET PIPE_EXECUTION_PAUSED = TRUE;

SELECT SYSTEM$PIPE_STATUS('PIPE_EMPLOYEES_CSV');

SELECT SYSTEM$PIPE_FORCE_RESUME('PIPE_EMPLOYEES_CSV');

ALTER PIPE HRMS.PIPE.PIPE_EMPLOYEES_CSV SET PIPE_EXECUTION_PAUSED = FALSE;


--Not Allowed for COPY into snowpipe In Some Cases---


CREATE OR REPLAC PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST = TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
ON_ERROR = 'ABORT_STATEMENT'

CREATE OR REPLAC PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST = TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
ON_ERROR = 'SKIP_FILE'


CREATE OR REPLAC PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST = TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
ON_ERROR = 'CONTINUE'


CREATE OR REPLAC PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST = TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
ON_ERROR = 'RETURN_ALL_ERRORS'
