USE HRMS;

CREATE OR REPLACE SCHEMA CDC;


CREATE OR REPLACE TABLE CDC.EMPLOYEES
(
EMPLOYEE_ID    NUMBER(10),
FIRST_NAME     VARCHAR(25),
LAST_NAME     VARCHAR(25),
EMAIL          VARCHAR(20),
PHONE_NUMBER   VARCHAR(20),
HIRE_DATE      DATE,
JOB_ID         VARCHAR(20),
SALARY         NUMBER(8,2),
COMMISSION_PCT  DECIMAL(2,2),
MANAGER_ID     NUMBER(6),
DEPARTMENT_ID  NUMBER(5)

);

INSERT INTO CDC.EMPLOYEES(EMPLOYEE_ID,FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(100, 'STEVEN', 'KING', 'SKING', '444.334.2005', TO_DATE('12-03-2023', 'dd-mm-yyyy'),'AD_PRES', '2400', NULL, 23, 45 );

INSERT INTO CDC.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT,MANAGER_ID, DEPARTMENT_ID )
VALUES(101, 'NEENA', 'KOCHAR', 'NKOCHAR', '444.334.2005', TO_DATE('12-03-2023', 'dd-mm-yyyy'),'AD_PRES', '2400', NULL, 24, 46 );

SELECT * FROM CDC.EMPLOYEES;

CREATE OR REPLACE TABLE EMPLOYEES_DIM_CDC
(
EMPLOYEE_ID    NUMBER(10),
FIRST_NAME     VARCHAR(25),
LAST_NAME     VARCHAR(25),
EMAIL          VARCHAR(20),
PHONE_NUMBER   VARCHAR(20),
HIRE_DATE      DATE,
JOB_ID         VARCHAR(20),
SALARY         NUMBER(8,2),
COMMISSION_PCT  DECIMAL(2,2),
MANAGER_ID     NUMBER(6),
DEPARTMENT_ID  NUMBER(5),
LAST_UPDATED_TS TIMESTAMP,
LAST_INSERTED_TS TIMESTAMP

);

CREATE OR REPLACE STREAM STREAM_EMPLOYEE ON TABLE CDC.EMPLOYEES;

SELECT * FROM STREAM_EMPLOYEE;

UPDATE CDC.EMPLOYEES
SET SALARY = 21000
WHERE EMPLOYEE_ID = 100;

UPDATE CDC.EMPLOYEES
SET SALARY = 18000
WHERE EMPLOYEE_ID = 101;

SELECT * FROM CDC.EMPLOYEES;

SELECT * FROM STREAM_EMPLOYEE;

INSERT INTO CDC.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT,MANAGER_ID, DEPARTMENT_ID )
VALUES(102, 'DEVI', 'MALLI', 'NKOCHAR', '444.334.2005', TO_DATE('12-03-2023', 'dd-mm-yyyy'),'AD_PRES', '3000', NULL, 27, 49 );

SELECT * FROM CDC.EMPLOYEES;

SELECT * FROM STREAM_EMPLOYEE;

MERGE INTO EMPLOYEES_DIM_CDC EDIM
USING STREAM_EMPLOYEE CDC
ON EDIM.EMPLOYEE_ID = CDC.EMPLOYEE_ID
WHEN MATCHED AND
    METADATA$ACTION = 'INSERT' AND
    METADATA$ISUPDATE = TRUE
THEN UPDATE
    SET
    EDIM.EMPLOYEE_ID    =   CDC.EMPLOYEE_ID,
    EDIM.FIRST_NAME     =   CDC.FIRST_NAME,
    EDIM.LAST_NAME      =   CDC.LAST_NAME,
    EDIM.EMAIL          =   CDC.EMAIL,
    EDIM.PHONE_NUMBER   =   CDC.PHONE_NUMBER,
    EDIM.HIRE_DATE      =   CDC.HIRE_DATE,
    EDIM.JOB_ID         =   CDC.JOB_ID,
    EDIM.SALARY         =   CDC.SALARY,
    EDIM.COMMISSION_PCT =  CDC.COMMISSION_PCT,
    EDIM.MANAGER_ID     =   CDC.MANAGER_ID,
    EDIM.DEPARTMENT_ID  =   CDC.DEPARTMENT_ID,
    EDIM.LAST_UPDATED_TS =  CURRENT_TIMESTAMP(),
    EDIM.LAST_INSERTED_TS =  CURRENT_TIMESTAMP() 
WHEN NOT MATCHED AND
        METADATA$ACTION = 'INSERT'

THEN INSERT (EDIM.EMPLOYEE_ID,EDIM.FIRST_NAME, EDIM.LAST_NAME,EDIM.EMAIL,EDIM.PHONE_NUMBER,EDIM.HIRE_DATE,EDIM.JOB_ID,EDIM.SALARY,EDIM.COMMISSION_PCT,EDIM.MANAGER_ID,EDIM.DEPARTMENT_ID,EDIM.LAST_UPDATED_TS,EDIM.LAST_INSERTED_TS)
VALUES(CDC.EMPLOYEE_ID,CDC.FIRST_NAME,CDC.LAST_NAME,CDC.EMAIL,CDC.PHONE_NUMBER,CDC.HIRE_DATE,CDC.JOB_ID,CDC.SALARY,CDC.COMMISSION_PCT,CDC.MANAGER_ID,CDC.DEPARTMENT_ID,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP())

   
SELECT * FROM EMPLOYEES_DIM_CDC EDIM;

SELECT * FROM STREAM_EMPLOYEE;

SELECT * FROM CDC.EMPLOYEES;

DELETE FROM CDC.EMPLOYEES
WHERE EMPLOYEE_ID = 101 AND FIRST_NAME = 'DEVI';

DELETE FROM CDC.EMPLOYEES
WHERE EMPLOYEE_ID = 100;

SELECT * FROM CDC.EMPLOYEES;

UPDATE CDC.EMPLOYEES
SET SALARY = 24000, JOB_ID = 'AD_PRES'
WHERE EMPLOYEE_ID = 101;

SELECT * FROM CDC.EMPLOYEES;

SELECT * FROM STREAM_EMPLOYEE;

MERGE INTO EMPLOYEES_DIM_CDC EDIM
USING STREAM_EMPLOYEE CDC
ON EDIM.EMPLOYEE_ID = CDC.EMPLOYEE_ID
WHEN MATCHED AND
    METADATA$ACTION = 'INSERT' AND
    METADATA$ISUPDATE = TRUE
THEN UPDATE
    SET
    EDIM.EMPLOYEE_ID    =   CDC.EMPLOYEE_ID,
    EDIM.FIRST_NAME     =   CDC.FIRST_NAME,
    EDIM.LAST_NAME      =   CDC.LAST_NAME,
    EDIM.EMAIL          =   CDC.EMAIL,
    EDIM.PHONE_NUMBER   =   CDC.PHONE_NUMBER,
    EDIM.HIRE_DATE      =   CDC.HIRE_DATE,
    EDIM.JOB_ID         =   CDC.JOB_ID,
    EDIM.SALARY         =   CDC.SALARY,
    EDIM.COMMISSION_PCT =  CDC.COMMISSION_PCT,
    EDIM.MANAGER_ID     =   CDC.MANAGER_ID,
    EDIM.DEPARTMENT_ID  =   CDC.DEPARTMENT_ID,
    EDIM.LAST_UPDATED_TS =  CURRENT_TIMESTAMP(),
    EDIM.LAST_INSERTED_TS =  CURRENT_TIMESTAMP() 
WHEN MATCHED AND METADATA$ACTION = 'DELETE'
                AND METADATA$ISUPDATE = FALSE
THEN DELETE

WHEN NOT MATCHED AND
    METADATA$ACTION = 'INSERT' AND
    METADATA$ISUPDATE = FALSE

THEN INSERT (EDIM.EMPLOYEE_ID,EDIM.FIRST_NAME, EDIM.LAST_NAME,EDIM.EMAIL,EDIM.PHONE_NUMBER,EDIM.HIRE_DATE,EDIM.JOB_ID,EDIM.SALARY,EDIM.COMMISSION_PCT,EDIM.MANAGER_ID,EDIM.DEPARTMENT_ID,EDIM.LAST_UPDATED_TS,EDIM.LAST_INSERTED_TS)
VALUES(CDC.EMPLOYEE_ID,CDC.FIRST_NAME,CDC.LAST_NAME,CDC.EMAIL,CDC.PHONE_NUMBER,CDC.HIRE_DATE,CDC.JOB_ID,CDC.SALARY,CDC.COMMISSION_PCT,CDC.MANAGER_ID,CDC.DEPARTMENT_ID,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());


SELECT * FROM EMPLOYEES_DIM_CDC;
