USE HRMS;

CREATE OR REPLACE SCHEMA SCHEDULE;

--Creating Tasks---

CREATE OR REPLACE TASK TASK_CREATE_TABLE
WAREHOUSE = COMPUTE_WH
SCHEDULE = '10 MINUTE'    ---1 MINUTE(S) | 35 MINUTE(S) | 60 MINUTE(S) | 120 MINUTE(S) | HOURS NOT ALLOWED
AS 
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES
AS 
SELECT * FROM HR.EMPLOYEES;

SHOW TASKS;

SHOW TASKS LIKE 'TASK_CREATE_TABLE';
DESCRIBE TASK TASK_CREATE_TABLE;

ALTER TASK TASK_CREATE_TABLE RESUME;

ALTER TASK TASK_CREATE_TABLE SUSPEND;

SHOW TABLES;

EXECUTE TASK TASK_CREATE_TABLE;


--Scheduling Task---

CREATE OR REPLACE TASK TASK_CREATE_TABLE
WAREHOUSE = COMPUTE_WH
SHEDULE = 'USING CRON 0 7 * * 1-5 America/California'          --Monday to Friday at 7.00am California Time.
AS
CREATE OR REPLACE TASK SCHEDULE.EMPLOYEES
AS
SELECT * FROM HR.EMPLOYEES;


#----------minitr (0-59)
#----------hour(0-23)
#----------day(1-31, or L)
#----------day of week (0-6, SUN_SAT, or L)

DORP TASK TASK_CREATE_TABLE;



---CReating Task without a shedule-----

CREATE OR REPLACE TASK TASK_CREATE_TABLE
WAREHOUSE = COMPUTE_WH
SCHEDULE = '10 MINUTE'    
AS 
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES_NOSCHEDULE
AS 
SELECT * FROM HR.EMPLOYEES;


ALTER TASK TASK_CREATE_TABLE RESUME;


EXECUTE TASK TASK_CREATE_TABLE;

SHOW TABLES;
SHOW TASKS;

--Creating Task without a warehouse----

CREATE OR REPLACE TASK TASK_CREATE_TABLE
--WAREHOUSE = COMPUTE_WH
SCHEDULE = '10 MINUTE'    
AS 
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES_NOWAREWOUSE
AS 
SELECT * FROM HR.EMPLOYEES;

EXECUTE TASK TASK_CREATE_TABLE;
SHOW TABLES;
SHOW TASKS;


--To resize the warehouse---


CREATE OR REPLACE TASK TASK_CREATE_TABLE
USER_TASK_MANAGED_INTIALLY_WAREHOUSE_SIZE = 'XLARGE'  ---DEFAULT MEDIUM.
SCHEDULE = '10 MINUTE'    
AS 
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES_NOWAREWOUSE_INTIAL_WAREHOUSE_SIZE
AS 
SELECT * FROM HR.EMPLOYEES;

ALTER TASK TASK_CREATE_TABLE RESUME;

EXECUTE TASK TASK_CREATE_TABLE;

SHOW TABLES;
SHOW TASKS;

---Using mor than 1 SQL statments with a TASK

CREATE OR REPLACE TASK TASK_CREATE_TABLE
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'    
AS 
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES_MULTISQL
AS 
SELECT * FROM HR.EMPLOYEES;
INSER INTO SCHEDULE.EMPLOYEES_MULTISQL (EMPLOYEE_ID, EMPLOYEE_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISION_PCT, MANAGER_ID,DEPARTMENT_ID) VALUES
(209,'JACK', 'JADAMS', '011.44.1644.429265',TO_DATE('23-04-2006', 'DD-MM-YYYY'),'SA_REP',8400,20,147,80)



--WE can not execute multiple sql statements, somtimes we need to execute it, so to overcome this we use BEGIN and END, we can write any num od sql staments inside this.---



CREATE OR REPLACE TASK TASK_CREATE_TABLE
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'    
AS 
BEGIN

CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES_MULTISQL
AS 
SELECT * FROM HR.EMPLOYEES;
WHERE 1=2;
INSER INTO SCHEDULE.EMPLOYEES_MULTISQL (EMPLOYEE_ID, EMPLOYEE_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISION_PCT, MANAGER_ID,DEPARTMENT_ID) VALUES
(209,'JACK', 'JADAMS', '011.44.1644.429265',TO_DATE('23-04-2006', 'DD-MM-YYYY'),'SA_REP',8400,20,147,80);

END;


ALTER TASK TASK_CREATE_TABLE RESUME;

EXECUTE TASK TASK_CREATE_TABLE;

SHOW TABLES;
SHOW TASKS;

