USE HRMS;

CREATE OR REPLACE SCHEMA SCHEDULE;

--Creating Tasks---

CREATE OR REPLACE TASK TASK_CREATE_TABLE
WAREHOUSE = COMPUTE_WH
SCHEDULE = '10 MINUTE'    ---1 MINUTE(S) | 35 MINUTE(S) | 60 MINUTE(S) | 120 MINUTE(S) | HOURS NOT ALLOWED
AS 
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES
AS 
SELECT * FROM HR.EMPLOYEES;

SHOW TASKS;

SHOW TASKS LIKE 'TASK_CREATE_TABLE';
DESCRIBE TASK TASK_CREATE_TABLE;

ALTER TASK TASK_CREATE_TABLE RESUME;

ALTER TASK TASK_CREATE_TABLE SUSPEND;

SHOW TABLES;

EXECUTE TASK TASK_CREATE_TABLE;


--Scheduling Task---

CREATE OR REPLACE TASK TASK_CREATE_TABLE
WAREHOUSE = COMPUTE_WH
SHEDULE = 'USING CRON 0 7 * * 1-5 America/California'          --Monday to Friday at 7.00am California Time.
AS
CREATE OR REPLACE TASK SCHEDULE.EMPLOYEES
AS
SELECT * FROM HR.EMPLOYEES;


#----------minitr (0-59)
#----------hour(0-23)
#----------day(1-31, or L)
#----------day of week (0-6, SUN_SAT, or L)

DORP TASK TASK_CREATE_TABLE;
