---Trubleshoot_snowpipe_error--

USE DATABASE HRMS;

CREATE OR REPLACE SCHEMA PIPE;

CREATE OR REPLACE FILE FARMAT HRMS.PIPE.CSV_PIPE_FILEFARMATE
FILE = CSV 
FIELD_DEILMETRY = ','
SKIP_HEADER = 0
FIELD_OPTIONALLY_ENCLOSED_BY = '""'
EMPTY_FIELD_AS_NULL = TRUE

CREATE OR REPLACE STAGE HRMS.PIPE.AWS_PIPE_CSV_STAGE
STORAGE_INTEGRATION = AWS_S3_INT
URL = 's3//learn2cloude-snowflake/snowpipe/csv/'
FILE_FARMATE = CSV_PIPE_FILEFARMAT


LIST @AWS_PIPE_CSV_STAGE;




CREATE OR REPLACE TABLE EMPLOYEES_SNOWPIPE_CSV_ERROR
(
EMPLOYEE_ID   NUMBER(6),
FIRST_NAME    VARCHAR(20),
LAST_NAME     VARCHAR(20),
EMAIL         VARCHAR(20),
PHONE_NUMBER  VARCHAR(20),
HIRE_DATE     VARCHAR(20),
JOB_ID        VARCHAR(20),
SALARY,        NUMBER(8,2)
COMMISION_PCT  NUMBER(2,2),
MANAGER_ID     NUMBER(6),
DEPARTMENT_ID  NUMBER(4)

);

CREATE OR REPLACE PIPE PIPE_EMPLOYEE_CSV_ERROR
AUTO_INGEST = TRUE
COPY INTO EMPLOYEES_SNOWPIPE_CSV_ERROR FROM @AWS_PIPE_CSV_STAGE;

SHOW PIPES;


SHOW PIPE LIKE 'PIPE_EMPLOYEE_CSV_ERROR';

SELECT SYSTEM$PIPE_STATUS('PIPE_EMPLOYEE_CSV_ERROR');

SELECT * FROM PIPE_EMPLOYEE_CSV_ERROR;

SELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY
    (
    TABLE_NAME = > 'EMPLOYEES_SNOWPIPE_CSV_ERROR '
    START_TIME => DATEADD(HOURS, -4, CURRENT_TIME_STAMP())
    )

);

SELECT * FROM TABLE(INFORMATION_SCHEMA.VALIDATE_PIPE_LOAD
    (
    PIPE_NAME = > 'PIPE_EMPLOYEE_CSV_ERROR'
    START_TIME => DATEADD(HOURS, -4, CURRENT_TIME_STAMP())
    )

);
